sudo: required
services:
  - docker

before_install:
  - docker build -t junhanng11/docker-react -f Dockerfile.dev .
script:
  - docker run -e CI=true junhanng11/docker-react npm run test -- --coverage